# Generated by Django 4.2.11 on 2024-03-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist", "0002_streamplatform_watchlist_delete_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waatchlist",
                to="watchlist.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
